DATA go_events TYPE REF TO zcl_dynscreen_events.
DATA gv_subrc TYPE sy-subrc.
SELECTION-SCREEN BEGIN OF SCREEN 0001 .
PARAMETERS V_0002 TYPE MARA-MATNR DEFAULT 'DEFAULT'.
PARAMETERS V_0003 TYPE MARA-MATNR.
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN PUSHBUTTON 01(20) BT_0004 USER-COMMAND UC_0004.
DATA DV_0005 TYPE VBAK-VBELN.
SELECT-OPTIONS V_0005 FOR DV_0005.
PARAMETERS V_0006 TYPE EKKO-EBELN.
SELECTION-SCREEN END OF SCREEN 0001.
LOAD-OF-PROGRAM.
BT_0004 = 'Testbutton'.
AT SELECTION-SCREEN.
  IF sy-ucomm = 'UC_0004'.
    sy-ucomm = go_events->raise( iv_id = '0004' iv_ucomm = sy-ucomm ).
  ENDIF.
IF sy-ucomm = '_%_%_EXIT_%_%_'.
LEAVE TO SCREEN 0.
ENDIF.
