CLASS zcl_dynscreen_screen DEFINITION PUBLIC INHERITING FROM zcl_dynscreen_screen_base FINAL CREATE PUBLIC.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_dynscreen_screen IMPLEMENTATION.
ENDCLASS.
